name: ci
on:
  push:
    branches-ignore:
    - 'master'
jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        run: |
          /usr/bin/docker run --name scanner -d sonarsource/sonar-scanner-cli:4.3 sleep 60
          /usr/bin/docker cp scanner:/opt/sonar-scanner sonar-scanner
          /usr/bin/docker rm -f scanner
          /usr/bin/docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file ./Dockerfile --push . \
          --tag registry.cn-shanghai.aliyuncs.com/c7n/cibase:${GITHUB_REF#refs/heads/}